# Generated by Django 4.0.1 on 2022-01-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': (('can_edit', 'Can edit the event'), ('cannot_book', 'Cannot book the event'))},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='avaliable',
            new_name='available',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='start time'),
        ),
    ]
