# Generated by Django 4.0.1 on 2022-01-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
